project_name: gitleaks

builds:
  - main: main.go
    binary: gitleaks
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X=github.com/zricethezav/gitleaks/v8/cmd.Version={{.Version}}
archives:
  - builds: [gitleaks]
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
release:
  prerelease: true
