name: Gitleaks Release
run-name: Gitleaks Release Run
on:
  push:
    branches:
      - 'master-uplus'
    tags:
      - 'v*.*.*-uplus*'

jobs:
  Release-Gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Print Release Version
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
