name: Gitleaks Release
run-name: Gitleaks Release Run
on:
  push:
    tags:
      - 'v*.*.*-uplus.*'

jobs:
  Release-Gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Release Version
        run: |
         echo `git tag | sort -V | tail -1`
        
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
