name: Gitleaks Release
run-name: Gitleaks Release Run
on:
  push:
    branches:
      - 'master-uplus'
    tags:
      - 'v*.*.*-uplus.*'

jobs:
  Release-Gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print Release Version
        run: |
         echo "Release Version is $TAG_NAME"
        
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
